import "./globals.css";
import React from "react";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/Navbar";
import StyledComponentsRegistry from "@/components/util/registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
           <head>
               <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
           </head>
            <body className={inter.className}>
                <StyledComponentsRegistry>
                    <div style={{ width: "100%" }}>
                        <Navbar />
                        {children}
                    </div>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
